/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ResponseData } from "./responsedata";
import { Expose, Type } from "class-transformer";

/**
 * Authentication Error
 */
export class ErrorResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ResponseData)
    error: ResponseData;
}
