/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Total cost details of shipment for buyer/importer. Only applicable to DDP shipments.
 */
export class LandedCostDetail extends SpeakeasyBase {
    /**
     * Fees for the order to be returned to the customer after business rules are applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "AIT" })
    ait: number;

    /**
     * Actual fees prior to any business being applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ActualAIT" })
    actualAIT: number;

    /**
     * Actual Duties prior to any business being applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ActualDuty" })
    actualDuty: number;

    /**
     * Actual Landed cost prior to any business being applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ActualLandedCost" })
    actualLandedCost: number;

    /**
     * Actual sales tax prior to any business being applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ActualSalesTax" })
    actualSalesTax: number;

    /**
     * Duties for the order to be returned to the customer after business rules are applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Duty" })
    duty: number;

    /**
     * The unique key of the landed cost
     */
    @SpeakeasyMetadata()
    @Expose({ name: "DutyHashKey" })
    dutyHashKey: string;

    /**
     * Landed cost (Duties/Taxes/Fees) for the order to be returned to the customer after business rules are applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "LandedCost" })
    landedCost: number;

    /**
     * Sales tax for the order to be returned to the customer after business rules are applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "SalesTax" })
    salesTax: number;
}
