/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MissingPropertyModel extends SpeakeasyBase {
    /**
     * missingProperty
     */
    @SpeakeasyMetadata()
    @Expose({ name: "missingProperty" })
    missingProperty?: string;
}
