/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Package extends SpeakeasyBase {
    /**
     * Height of the parcel when empty
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Height" })
    height?: number;

    /**
     * Length of the parcel when empty
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Length" })
    length?: number;

    /**
     * Total actual (scaled) weight of the package
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Weight" })
    weight: number;

    /**
     * Width of the parcel when empty
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Width" })
    width?: number;
}
