/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TradeModel } from "./trademodel";
import { Expose, Type } from "class-transformer";

/**
 * Model representing the response data provided from requests to POST /Rates for retrieving rates.
 */
export class RatesResponse extends SpeakeasyBase {
    /**
     * currency for the rate
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Currency" })
    currency: string;

    /**
     * Provides details for DDP and DDU terms
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Economy" })
    @Type(() => TradeModel)
    economy?: TradeModel;

    /**
     * Provides details for DDP and DDU terms
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Express" })
    @Type(() => TradeModel)
    express?: TradeModel;

    /**
     * Unique id that can be used to retrieve rate later if needed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "RateId" })
    rateId: number;

    /**
     * The reference id that was sent in the request. The intent of this id is for you to correlate the requests and responses
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Reference" })
    reference: string;

    /**
     * Unique identifier for the request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "RootRequestId" })
    rootRequestId: string;

    /**
     * Provides details for DDP and DDU terms
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Standard" })
    @Type(() => TradeModel)
    standard?: TradeModel;
}
