/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ResponseDetails } from "./responsedetails";
import { Expose, Type } from "class-transformer";

export class ResponseData extends SpeakeasyBase {
    /**
     * code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code: string;

    @SpeakeasyMetadata({ elemType: ResponseDetails })
    @Expose({ name: "details" })
    @Type(() => ResponseDetails)
    details?: ResponseDetails[];

    /**
     * Message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message: string;

    /**
     * name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * requestId
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requestId" })
    requestId?: string;

    /**
     * number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "statusCode" })
    statusCode: number;
}
