/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MissingPropertyModel } from "./missingpropertymodel";
import { Expose, Type } from "class-transformer";

export class ResponseDetails extends SpeakeasyBase {
    /**
     * code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "info" })
    @Type(() => MissingPropertyModel)
    info?: MissingPropertyModel;

    /**
     * message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    /**
     * path
     */
    @SpeakeasyMetadata()
    @Expose({ name: "path" })
    path?: string;
}
