/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Possible values could be 'STANDARD' | 'EXPRESS' | 'ECONOMY'. Default is ['STANDARD', 'EXPRESS', 'ECONOMY']
 */
export enum ServiceCode {
    Standard = "STANDARD",
    Express = "EXPRESS",
    Economy = "ECONOMY",
}
