/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ShipFromAddress extends SpeakeasyBase {
    /**
     * First line of the address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "AddressLine1" })
    addressLine1: string;

    /**
     * Second line of the address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "AddressLine2" })
    addressLine2?: string;

    /**
     * Third line of the address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "AddressLine3" })
    addressLine3?: string;

    /**
     * Name of attention, if person
     */
    @SpeakeasyMetadata()
    @Expose({ name: "AttentionName" })
    attentionName: string;

    /**
     * Full city name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "City" })
    city: string;

    /**
     * ISO 3166 Country Code. https://www.iso.org/iso-3166-country-codes.html
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Country" })
    country: string;

    /**
     * Email to reach the person or organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Email" })
    email: string;

    /**
     * Name of person. Both name and company can be included
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Name" })
    name: string;

    /**
     * Phone number to reach the person or organization
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Phone" })
    phone: string;

    /**
     * ISO 3166-2 State or Province Code Only. https://www.iso.org/standard/72483.html
     */
    @SpeakeasyMetadata()
    @Expose({ name: "State" })
    state?: string;

    /**
     * ZIP or postal code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "Zip" })
    zip: string;
}
