/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Terms of trade can be Delivery Duty Paid (DDP) or Delivery Duty Unpaid (DDU). Default is ['DDU', 'DDP']
 */
export enum TermsOfTrade {
    Ddp = "DDP",
    Ddu = "DDU",
}
