/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RateDetailDDP } from "./ratedetailddp";
import { RateDetailDDU } from "./ratedetailddu";
import { Expose, Type } from "class-transformer";

/**
 * Provides details for DDP and DDU terms
 */
export class TradeModel extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "DDP" })
    @Type(() => RateDetailDDP)
    ddp?: RateDetailDDP;

    @SpeakeasyMetadata()
    @Expose({ name: "DDU" })
    @Type(() => RateDetailDDU)
    ddu?: RateDetailDDU;
}
